USE [EScooterDB]
GO

/****** Object:  Table [dbo].[RidesMin]    Script Date: 17.07.2025 11:10:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RidesMin](
	[RideID] [int] IDENTITY(1,1) NOT NULL,
	[Minutes] [float] NOT NULL,
	[Fare] [decimal](10, 2) NOT NULL,
	[RideDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[RideID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RidesMin] ADD  DEFAULT (getdate()) FOR [RideDate]
GO

